services:
  # 1. API Principal (FastAPI)
  bec_api:
    build:
      context: ./BEC_API
    container_name: bec_api_app
    restart: unless-stopped
    ports:
      - "8000:5000"
    volumes:
      - ./BEC_API:/app
    environment:
      # Credenciales BD y llave secreta JWT
      - DATABASE_URL=postgresql://postgres:12345@db_postgres:5432/BEC
      - SECRET_KEY=BEC_Sistemas_Inteligentes_2026_Secret
    depends_on:
      # La API espera a que la BD esté lista
      - db_postgres
    networks:
      - bec_network

  # 2. Portal Centros (Flask)
  bec_pcf:
    build:
      context: ./BEC_PCF
    container_name: bec_pcf_app
    restart: unless-stopped
    ports:
      - "8001:5000"
    volumes:
      - ./BEC_PCF:/app
    networks:
      - bec_network

  # 3. Portal Receptores (Flask)
  bec_prf:
    build:
      context: ./BEC_PRF
    container_name: bec_prf_app
    restart: unless-stopped
    ports:
      - "8002:5000"
    volumes:
      - ./BEC_PRF:/app
    networks:
      - bec_network

  # 4. Portal Admin (Laravel)
  bec_pal:
    build:
      context: ./BEC_PAL
    container_name: bec_pal_app
    restart: unless-stopped
    ports:
      - "8003:8000"
    working_dir: /app
    volumes:
      - ./BEC_PAL:/app
    networks:
      - bec_network

  # Base de Datos PostgreSQL
  db_postgres:
    image: postgres:15-alpine
    container_name: bec_db_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: BEC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bec_network

# ==========================================
# AQUÍ ESTÁ LA SOLUCIÓN AL ERROR:
# Declaramos la red para que exista
# ==========================================
networks:
  bec_network:
    driver: bridge

volumes:
  postgres_data: # <--- NUEVO: Guarda la info de Postgres físicamente
