"""agregar ubicacion a voluntariados

Revision ID: 6c210e1e6617
Revises: 58aa864f651d
Create Date: 2026-08-02 15:28:53.116219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c210e1e6617'
down_revision: Union[str, None] = '58aa864f651d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voluntariados', sa.Column('ubicacion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voluntariados', 'ubicacion')
    # ### end Alembic commands ###
