"""agregar encargados de voluntariado y estado no asistio

Revision ID: 74c1a0272059
Revises: 2b53f6b8d1a8
Create Date: 2026-08-03 22:20:39.941491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c1a0272059'
down_revision: Union[str, None] = '2b53f6b8d1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voluntariados_encargados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voluntariado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['voluntariado_id'], ['voluntariados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voluntariado_id', 'usuario_id', name='uq_encargado_voluntariado_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voluntariados_encargados')
    # ### end Alembic commands ###
