"""esquema inicial

Revision ID: 8282a0a46fe6
Revises: 
Create Date: 2026-08-02 06:35:45.427636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8282a0a46fe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('condiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados_inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados_voluntariado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_objetivos', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_campanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codigos_postales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_postal', sa.String(length=5), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('colonia', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_postales_codigo_postal'), 'codigos_postales', ['codigo_postal'], unique=False)
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('colonia', sa.String(length=150), nullable=False),
    sa.Column('calle', sa.String(length=150), nullable=False),
    sa.Column('numero_exterior', sa.String(length=20), nullable=False),
    sa.Column('numero_interior', sa.String(length=20), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albergues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('capacidad_max', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('albergue_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('terminos_aceptados', sa.Boolean(), nullable=False),
    sa.Column('fecha_aceptacion_terminos', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['albergue_id'], ['albergues.id'], ),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('voluntariados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_programa', sa.String(length=150), nullable=False),
    sa.Column('albergue_id', sa.Integer(), nullable=True),
    sa.Column('campana_id', sa.Integer(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('cupo_maximo', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_requisitos', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['albergue_id'], ['albergues.id'], ),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_voluntariado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('condicion_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('albergue_id', sa.Integer(), nullable=False),
    sa.Column('fecha_donacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['albergue_id'], ['albergues.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['condicion_id'], ['condiciones.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones_voluntariados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('voluntariado_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cancelacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_inscripcion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['voluntariado_id'], ['voluntariados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'voluntariado_id', name='uq_inscripcion_usuario_voluntariado')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('plataforma', sa.String(length=30), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_refresh_token_hash'), 'sesiones', ['refresh_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesiones_refresh_token_hash'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_table('inscripciones_voluntariados')
    op.drop_table('donaciones')
    op.drop_table('voluntariados')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('albergues')
    op.drop_table('direcciones')
    op.drop_index(op.f('ix_codigos_postales_codigo_postal'), table_name='codigos_postales')
    op.drop_table('codigos_postales')
    op.drop_table('campanas')
    op.drop_table('unidades')
    op.drop_table('roles')
    op.drop_table('generos')
    op.drop_table('estados_voluntariado')
    op.drop_table('estados_inscripcion')
    op.drop_table('estados_campanas')
    op.drop_table('estados')
    op.drop_table('condiciones')
    op.drop_table('categorias')
    # ### end Alembic commands ###
