"""agregar codigo de recuperacion de password a usuarios

Revision ID: b7d88c9f0aa7
Revises: 74c1a0272059
Create Date: 2026-08-03 23:56:15.302508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d88c9f0aa7'
down_revision: Union[str, None] = '74c1a0272059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_password_codigo_hash', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('reset_password_expira_en', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'reset_password_expira_en')
    op.drop_column('usuarios', 'reset_password_codigo_hash')
    # ### end Alembic commands ###
