"""soft delete con purga, veto y rate limiting de login

Revision ID: ca1cf3b93ce1
Revises: 6c210e1e6617
Create Date: 2026-08-02 21:23:35.699616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1cf3b93ce1'
down_revision: Union[str, None] = '6c210e1e6617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intentos_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('bloqueado_hasta', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_login_correo'), 'intentos_login', ['correo'], unique=True)
    op.add_column('albergues', sa.Column('fecha_desactivacion', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('donaciones', 'albergue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inscripciones_voluntariados', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('usuarios', sa.Column('fecha_desactivacion', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('vetado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('usuarios', sa.Column('motivo_veto', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'motivo_veto')
    op.drop_column('usuarios', 'vetado')
    op.drop_column('usuarios', 'fecha_desactivacion')
    op.alter_column('inscripciones_voluntariados', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donaciones', 'albergue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('albergues', 'fecha_desactivacion')
    op.drop_index(op.f('ix_intentos_login_correo'), table_name='intentos_login')
    op.drop_table('intentos_login')
    # ### end Alembic commands ###
