FROM php:8.2-cli

# Instalamos dependencias básicas del sistema
RUN apt-get update && apt-get install -y \
    git curl libpng-dev libonig-dev libxml2-dev zip unzip

# Limpiamos caché
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalamos extensiones de PHP que usa Laravel
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instalamos Composer dentro del contenedor
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Nos movemos a la carpeta /app
WORKDIR /app

# Exponemos el puerto
EXPOSE 8000

# Arrancamos el servidor de Laravel
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]